
 1- TÖLLNER SEPSİS FORMU


-- 1. Deri Renginde Değişiklik
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Deri Renginde Değişiklik', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yok', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Orta', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Belirgin', 1, 2);


-- 2. Periferik Dolaşım Bozukluğu
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Periferik Dolaşım Bozukluğu', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yok', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Bozuk', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Belirgin', 1, 2);


-- 3. Hipotoni
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Hipotoni', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yok', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Orta', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Belirgin', 1, 2);


-- 4. Bradikardi
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Bradikardi', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yok', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Var', 1, 1);


-- 5. Apne
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Apne', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yok', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Var', 1, 1);


-- 6. Respiratuar distres
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Respiratuar distres', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yok', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Var', 1, 1);


-- 7. Hepatomegali (Tablondaki HEPATOMEGALI ile birebir esitlendi)
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Hepatomegali', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yok', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), '>4 cm', 1, 1);


-- 8. Gastrointestinal Bulgu
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Gastrointestinal Bulgu', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yok', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Var', 1, 1);


-- 9. Lökosit Sayısı
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Lökosit Sayısı', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Normal', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Lökositoz', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Lökopeni', 1, 2);


-- 10. Sola Kayma
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Sola Kayma', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yok', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Orta', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Belirgin', 1, 2);


-- 11. Trombositopeni
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Trombositopeni', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yok', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Var', 1, 1);


-- 12. Metabolik Asidoz
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Töllner Sepsis Formu', 'Metabolik Asidoz', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yok', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), '>7.2', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), '<7.2', 1, 2);

COMMIT;


 2- MODİFİYE ALDRETE SKORU


-- 1. Bilinç Düzeyi
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Modifiye Aldrete Skoru', 'Bilinç Düzeyi', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Uyandırması Kolay', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Uyandırması Zor', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Yanıt Yok', 1, 0);


-- 2. Aktivite
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Modifiye Aldrete Skoru', 'Aktivite', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'İstemli yada emirle bütün ekstremiteler hareketli', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hareket etmek kısıtlı, zor', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hareket yok', 1, 0);


-- 3. Solunum
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Modifiye Aldrete Skoru', 'Solunum', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Desteksiz rahat solunum', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Dispneik yetersiz solunum', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Apnek', 1, 0);


-- 4. SpO2
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Modifiye Aldrete Skoru', 'SpO2', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'SpO2>94 % oda havasında', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'SpO2>94 % olması için O2 desteği gerekiyor', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'SpO2>94 % O2 desteğinde', 1, 0);


-- 5. Kan Basıncı
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Modifiye Aldrete Skoru', 'Kan Basıncı', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'TA işlem sonrası değerinde ± 20mm Hg farklı', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'TA işlem sonrası değerinde ± 20-50mm Hg farklı', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'TA işlem sonrası değerinde ± 50mm Hg farklı', 1, 0);


-- 6. Nabız
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Modifiye Aldrete Skoru', 'Nabız', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'İşlem öncesi değerlerin %20''si içinde', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'İşlem öncesi değerlerin %20-40''ı içinde', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'İşlem öncesi değerlerin %40''ı içinde', 1, 0);

COMMIT;


3- EDINBURGH POSTPARTUM DEPRESYON ÖLÇEĞİ


-- 1. Soru: Gülebiliyor ve olayların komik tarafını görebiliyorum. (Ters Puanlama: 0 -> 3)
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Edinburgh Postpartum Depresyon Ölçeği', 'Gülebiliyor ve olayların komik tarafını görebiliyorum.', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Her zaman olduğu kadar', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Artık o kadar değil', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Artık kesinlikle o kadar değil', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Artık hiç değil', 1, 3);


-- 2. Soru: Geleceğe hevesle bakıyorum. (Ters Puanlama: 0 -> 3)
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Edinburgh Postpartum Depresyon Ölçeği', 'Geleceğe hevesle bakıyorum.', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Her zaman olduğu kadar', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Her zamankinden biraz az', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Her zamankinden kesinlikle daha az', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hemen hemen hiç', 1, 3);


-- 3. Soru: Bir şeyler kötü gittiğinde gereksiz yere kendimi suçluyorum. (Düz Puanlama: 3 -> 0)
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Edinburgh Postpartum Depresyon Ölçeği', 'Bir şeyler kötü gittiğinde gereksiz yere kendimi suçluyorum.', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, çoğu zaman', 1, 3);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, bazen', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Çok sık değil', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hayır, hiçbir zaman', 1, 0);


-- 4. Soru: Nedensiz yere kendimi sıkıntılı ya da endişeli hissediyorum. (Düz Puanlama: 0 -> 3)
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Edinburgh Postpartum Depresyon Ölçeği', 'Nedensiz yere kendimi sıkıntılı ya da endişeli hissediyorum.', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hayır, hiçbir zaman', 1, 0);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Çok seyrek', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, bazen', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, çoğu zaman', 1, 3);


-- 5. Soru: İyi bir nedeni olmadığı halde, korkuyor ya da panikliyorum. (Düz Puanlama: 3 -> 0)
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Edinburgh Postpartum Depresyon Ölçeği', 'İyi bir nedeni olmadığı halde, korkuyor ya da panikliyorum.', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, çoğu zaman', 1, 3);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, bazen', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hayır, çok sık değil', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hayır, hiçbir zaman', 1, 0);


-- 6. Soru: Her şey giderek sırtıma yükleniyor. (Düz Puanlama: 3 -> 0)
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Edinburgh Postpartum Depresyon Ölçeği', 'Her şey giderek sırtıma yükleniyor.', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, çoğu zaman hiç başa çıkamıyorum', 1, 3);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, bazen eskisi gibi başa çıkamıyorum', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hayır, çoğu zaman oldukça iyi başa çıkabiliyorum', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hayır, her zamanki gibi başa çıkabiliyorum', 1, 0);


-- 7. Soru: Öylesine mutsuzum ki uyumakta zorlanıyorum suçluyorum. (Düz Puanlama: 3 -> 0)
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Edinburgh Postpartum Depresyon Ölçeği', 'Öylesine mutsuzum ki uyumakta zorlanıyorum suçluyorum.', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, çoğu zaman', 1, 3);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, bazen', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hayır, çok sık değil', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hayır, hiçbir zaman', 1, 0);


-- 8. Soru: Kendimi üzüntülü ya da çökkün hissediyorum. (Düz Puanlama: 3 -> 0)
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Edinburgh Postpartum Depresyon Ölçeği', 'Kendimi üzüntülü ya da çökkün hissediyorum.', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, çoğu zaman', 1, 3);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, oldukça sık', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Çok seyrek', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hayır, hiçbir zaman', 1, 0);


-- 9. Soru: Öylesine mutsuzum ki ağlıyorum. (Düz Puanlama: 3 -> 0)
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Edinburgh Postpartum Depresyon Ölçeği', 'Öylesine mutsuzum ki ağlıyorum.', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, çoğu zaman', 1, 3);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, oldukça sık', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Çok seyrek', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hayır, hiçbir zaman', 1, 0);


-- 10. Soru: Kendime zarar verme düşüncesinin aklıma geldiği oldu. (Düz Puanlama: 3 -> 0)
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Edinburgh Postpartum Depresyon Ölçeği', 'Kendime zarar verme düşüncesinin aklıma geldiği oldu.', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, oldukça sık', 1, 3);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Bazen', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hemen hemen hiç', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Asla', 1, 0);


-- 11. Soru (Alternatif Metin): Öylesine mutsuzum ki içimden ağlamak geliyor veya ağlıyorum.
INSERT INTO MC_PARAMETERS (ID, MC_NAME, NAME, NOTE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS), 'Edinburgh Postpartum Depresyon Ölçeği', 'Öylesine mutsuzum ki içimden ağlamak geliyor veya ağlıyorum.', NULL);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, çoğu zaman', 1, 3);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Evet, oldukça sık', 1, 2);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Çok seyrek', 1, 1);

INSERT INTO MC_PARAMETERS_DETAIL (ID, MCP_ID, NAME, IS_ACTIVE, VALUE)
VALUES ((SELECT NVL(MAX(ID), 0) + 1 FROM MC_PARAMETERS_DETAIL), (SELECT MAX(ID) FROM MC_PARAMETERS), 'Hayır, hiçbir zaman', 1, 0);

COMMIT;
